[package]
name = "klotho-web"
rust-version.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
klotho-core.workspace = true
jiff.workspace = true
serde.workspace = true
topcoat = { workspace = true, features = ["default", "tailwind", "tower"] }
tracing.workspace = true

[build-dependencies]
topcoat = { workspace = true, features = ["tailwind"] }
